### ISSUE TITLE
Fix `isDateValid` check

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#115]
An illegal date like `31-02-23` will be considered to be valid, which means that a subsequent round of exception handling when cast to `Date` will have to be done. Modify to change the logic (e.g. just use `Date` casting to handle the check logic?)

**Comment by woodenclock** [comment]
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/19c013b5-6f94-4152-9dc0-1cec33578624)
Yup, right now, if the date exceeds max, it will just put max, but will fix in the future

**Comment by woodenclock** [comment]
Improved isDateValid to identify invalid dates, which takes into account the leap day, days in different months.
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/948dc325-222b-4a8e-9fe9-d0bfbbc87b8c)
