### ISSUE TITLE
[PE-D][Tester A] Summary of non-existing species raise error

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113T-W11-2/tp#137]
![image.png](https://raw.githubusercontent.com/ICubE-/ped/main/files/575d6be7-5361-4c7a-b9c5-ba1bfc32442d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ICubE-/ped#1

**Comment by imaginarys96** [comment]
fixed in commit 2d091add18b4a02eb73a20675005cbf43aee651c
