### ISSUE TITLE
[PE-D][Tester C] Error in parsing summary command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113T-W11-2/tp#145]
The program crashes when the summary command has an invalid <SPECIES> input. Perhaps the error should be caught and handled to prevent the program from crashing.

![image.png](https://raw.githubusercontent.com/NaychiMin/ped/main/files/a4629a6b-3e29-437c-a969-915e10d983dd.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: NaychiMin/ped#3

**Comment by imaginarys96** [comment]
fixed in 2d091add18b4a02eb73a20675005cbf43aee651c
