### ISSUE TITLE
[PE-D][Tester A] Weird export confirm message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113T-W11-2/tp#146]
The confirm message that export has succeeded is somewhat weird:

`WildWatch.csv has been written to!`

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ICubE-/ped#3

**Comment by lctxct** [comment]
Closed by https://github.com/AY2324S1-CS2113T-W11-2/tp/pull/186.
