### ISSUE TITLE
[PE-D][Tester B] Failed to further validate yes/no choice for delete function

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113T-W11-2/tp#151]
![屏幕截图 2023-11-03 170706.png](https://raw.githubusercontent.com/J-Y-Yan/ped/main/files/32ab5f96-5d4b-4baf-95be-c07ec97e5192.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: J-Y-Yan/ped#4

**Comment by woodenclock** [comment]
Fix bug: [PE-D][Tester B] Failed to further validate yes/no choice for delete function #151
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/d5dc5720-eef8-4077-815b-1932db3d70d3)
