### ISSUE TITLE
[PE-D][Tester B] ***Crash when using Summary with invalid input***

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113T-W11-2/tp#153]
![屏幕截图 2023-11-03 171036.png](https://raw.githubusercontent.com/J-Y-Yan/ped/main/files/92a62e10-2461-417c-ad84-b1cb6c0a631f.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: J-Y-Yan/ped#5

**Comment by imaginarys96** [comment]
fixed in 2d091add18b4a02eb73a20675005cbf43aee651c
