### ISSUE TITLE
[PE-D][Tester A] Unexpected behavior while requesting help of invalid command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113T-W11-2/tp#158]
![image.png](https://raw.githubusercontent.com/ICubE-/ped/main/files/9a1e16de-8198-4ce2-bc4a-bea74b6754c2.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ICubE-/ped#7

**Comment by woodenclock** [comment]
Fixed this bug.
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/e2f6da7f-3e35-4537-97ef-0cbdbb368f01)
