### ISSUE TITLE
[PE-D] `help` command issues 

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#189]
**Missing command descriptions**
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/156
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/160
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/161
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/171

**Others**
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/158, https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/175

**Comment by imaginarys96** [comment]
first and third issue are the same. resolved in 75355ac7c270ef78df951420c0eb6f4eb70023c0

**Comment by woodenclock** [comment]
Fixed the last issue
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/14c8f9e9-93f4-4bc6-a969-05248ebfce9e)
