### ISSUE TITLE
[PE-D] UG issues

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#190]
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/150
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/154
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/167
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/168
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/173

**Comment by woodenclock** [comment]
@lctxct for #167, do you want to make the Name part optional?????

**Comment by lctxct** [comment]
> @lctxct for #167, do you want to make the Name part optional?????

Since we won't be allowing duplicate entries (as per https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/159), we need Name to be specified to perform the check. So it's better to not make it optional.
