### ISSUE TITLE
[PE-D] `summary` command issues

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#191]
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/137, https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/145, https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/153, https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/172
- [x] https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/155

**Comment by imaginarys96** [comment]
first issue fixed in 2d091add18b4a02eb73a20675005cbf43aee651c (checks if species exist when running `summary` command)

**Comment by woodenclock** [comment]
For #155, it has been fixed.
But needs to improve on the case-sensitivity
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/11014a9a-a398-4516-8112-694e1469120b)

**Comment by woodenclock** [comment]
Fixed it!
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/6dbc1783-6e2a-41c4-aecc-cdf6bb6c29cb)
