### ISSUE TITLE
Final UG updates

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#205]
- [x] Specify to user that `(date, species, name)` must be unique (i.e. only one entry allowed to be made per animal per day) if https://github.com/AY2324S1-CS2113T-W11-2/tp/pull/204 goes through
- [x] I think if we have time, it was heavily implied that we should show screenshots of the process of opening command prompt, we can include that in appendix also (we can insert gifs into markdown actually, we could consider doing that, not sure what you all think?)

**Comment by woodenclock** [comment]
You mean for the Quick Start?
To show the start up process?

**Comment by lctxct** [comment]
I actually meant instructions on how to open command prompt, but I realized that's quite system specific...nvm...

**Comment by woodenclock** [comment]
Yup added into UG
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/9309285c-ed59-447d-a64f-3712c0a49f4e)

**Comment by woodenclock** [comment]
Added these for opening of command prompt
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/70333e7c-da6b-421d-b531-5f30d7db20ca)
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/7fd7c1a7-8c0d-42e0-835c-cad4b712f884)
