### ISSUE TITLE
Improve Help command

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#54]
- [x] Modify `help` page to be shorter so that it's easier for users to view all commands in one go 
- [x] Allow extended `help` commands (e.g. `help add` shows more info about help command, like examples of usage)
- [ ] Add `export` (usage: `export <filename>`, where `filename` is optional)

**Comment by woodenclock** [comment]
LGTM.
Will be closing this issue, as we're wrapping up and releasing v2.0
