### ISSUE TITLE
Extend `delete` command to allow for batch deletes

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#57]
Allow for batch deletes by searching for specific keywords. 

E.g. `delete S/species` will delete all of that species. 

Be sure to list everything about to be deleted and ask for confirmation before deleting.

**Comment by woodenclock** [comment]
Is there enough time for this?

**Comment by woodenclock** [comment]
I think this feature can be implemented in the future iterations.
