### ISSUE TITLE
Add task list

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#61]
Would be similar to `Duke`, can have the following features: 

**Minimal**
- task contains description
- can add / delete / list
(maybe can be something like:) 
```
task list
task add <description>
task delete <index>
```

**Enhancements**
- can have mark / unmark 
- associated date

**Comment by woodenclock** [comment]
This would likely not be feature in v2.1.
Maybe future iterations will have this feature
