### ISSUE TITLE
[UG] Write purpose of guide

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#66]
* Make sure that target audience of guide is mentioned

**Comment by woodenclock** [comment]
Oops, accidentally clicked on close

**Comment by woodenclock** [comment]
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/275b8077-34e2-4cb9-a066-af98504729da)
Target audience is mentioned
Purpose is stated
