### ISSUE TITLE
[UG] Include overview

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#67]

**Comment by woodenclock** [comment]
Introduction has been made according to the rubrics
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/f99fc3a0-0179-4066-bb93-e908f043852a)
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/c2f6e899-2fda-44b6-b8e5-2248bebbee61)
