### ISSUE TITLE
[UG] Add steps to check Java version

### ISSUE THREAD

**Issue by lctxct** [AY2324S1-CS2113T-W11-2/tp#68]

**Comment by woodenclock** [comment]
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/44d3e545-0e89-4260-885b-c1eb4d3b1060)
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/0bde392c-e00b-4ef6-9670-7ccd4e48c704)

**Comment by woodenclock** [comment]
Added a way for users to check their Java version
