### ISSUE TITLE
Code Review - Sungmin

### ISSUE THREAD

**Issue by Musfirahe0556596** [AY2324S1-CS2113T-W11-2/tp#80]
- InputHandler.java: lines 22-30: Could be further abstracted to improve code quality.
- UI.java: line 122-123: Empty line between description and parameter section.
- UI.java: line 147: Do remember to include JavaDoc comments, along with other methods too!
- FindCommand.java: line 23: 'Magic number' 5 - Could be placed as a named constant.
- FileHandler.java: 102-104: Punctuation behind each parameter description.

**Comment by woodenclock** [comment]
Thank you Muzfirah.
I have made the appropriate changes according to your review.
