### ISSUE TITLE
Format optional arguments in User Guide

### ISSUE THREAD

**Issue by imaginarys96** [AY2324S1-CS2113T-W11-2/tp#93]
Once we decided how to format optional arguments, update the User Guide accordingly.

Commands that have optional arguments (add accordingly):
`summary`  - `<SPECIES>` is optional
`edit` - `<DATE>`, `<SPECIES>`, `<NAME>`, `<REMARK>` is optional (i.e. when editing, you can just edit edit one field - you don't have to input all 4 fields to edit)
`add` - I think `<REMARK>` for `add` is optional (please confirm)

**Comment by woodenclock** [comment]
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/5d2c77af-74e1-49e6-bb8a-ab5953d7b4b7)
